// Generated by gencpp from file sss_package/GeolocatedObjectList.msg
// DO NOT EDIT!


#ifndef SSS_PACKAGE_MESSAGE_GEOLOCATEDOBJECTLIST_H
#define SSS_PACKAGE_MESSAGE_GEOLOCATEDOBJECTLIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sss_package/GeolocatedObject.h>

namespace sss_package
{
template <class ContainerAllocator>
struct GeolocatedObjectList_
{
  typedef GeolocatedObjectList_<ContainerAllocator> Type;

  GeolocatedObjectList_()
    : header()
    , objects()  {
    }
  GeolocatedObjectList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::sss_package::GeolocatedObject_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::sss_package::GeolocatedObject_<ContainerAllocator> >> _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::sss_package::GeolocatedObjectList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sss_package::GeolocatedObjectList_<ContainerAllocator> const> ConstPtr;

}; // struct GeolocatedObjectList_

typedef ::sss_package::GeolocatedObjectList_<std::allocator<void> > GeolocatedObjectList;

typedef boost::shared_ptr< ::sss_package::GeolocatedObjectList > GeolocatedObjectListPtr;
typedef boost::shared_ptr< ::sss_package::GeolocatedObjectList const> GeolocatedObjectListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sss_package::GeolocatedObjectList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sss_package::GeolocatedObjectList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sss_package::GeolocatedObjectList_<ContainerAllocator1> & lhs, const ::sss_package::GeolocatedObjectList_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.objects == rhs.objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sss_package::GeolocatedObjectList_<ContainerAllocator1> & lhs, const ::sss_package::GeolocatedObjectList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sss_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sss_package::GeolocatedObjectList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sss_package::GeolocatedObjectList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sss_package::GeolocatedObjectList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sss_package::GeolocatedObjectList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sss_package::GeolocatedObjectList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sss_package::GeolocatedObjectList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sss_package::GeolocatedObjectList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "137da611e49ad8c24c63b5e9c7e9e282";
  }

  static const char* value(const ::sss_package::GeolocatedObjectList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x137da611e49ad8c2ULL;
  static const uint64_t static_value2 = 0x4c63b5e9c7e9e282ULL;
};

template<class ContainerAllocator>
struct DataType< ::sss_package::GeolocatedObjectList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sss_package/GeolocatedObjectList";
  }

  static const char* value(const ::sss_package::GeolocatedObjectList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sss_package::GeolocatedObjectList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"sss_package/GeolocatedObject[] objects\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sss_package/GeolocatedObject\n"
"string object_class\n"
"float32 confidence\n"
"\n"
"float64 latitude\n"
"float64 longitude\n"
"\n"
"uint32 ping_index\n"
"time ping_stamp\n"
"float32 centroid_x_px\n"
"float32 centroid_y_px\n"
"\n"
"int32 bbox_x_px\n"
"int32 bbox_y_px\n"
"int32 bbox_width_px\n"
"int32 bbox_height_px\n"
;
  }

  static const char* value(const ::sss_package::GeolocatedObjectList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sss_package::GeolocatedObjectList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GeolocatedObjectList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sss_package::GeolocatedObjectList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sss_package::GeolocatedObjectList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::sss_package::GeolocatedObject_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SSS_PACKAGE_MESSAGE_GEOLOCATEDOBJECTLIST_H
