// Generated by gencpp from file sss_package/GeolocatedObject.msg
// DO NOT EDIT!


#ifndef SSS_PACKAGE_MESSAGE_GEOLOCATEDOBJECT_H
#define SSS_PACKAGE_MESSAGE_GEOLOCATEDOBJECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sss_package
{
template <class ContainerAllocator>
struct GeolocatedObject_
{
  typedef GeolocatedObject_<ContainerAllocator> Type;

  GeolocatedObject_()
    : object_class()
    , confidence(0.0)
    , latitude(0.0)
    , longitude(0.0)
    , ping_index(0)
    , ping_stamp()
    , centroid_x_px(0.0)
    , centroid_y_px(0.0)
    , bbox_x_px(0)
    , bbox_y_px(0)
    , bbox_width_px(0)
    , bbox_height_px(0)  {
    }
  GeolocatedObject_(const ContainerAllocator& _alloc)
    : object_class(_alloc)
    , confidence(0.0)
    , latitude(0.0)
    , longitude(0.0)
    , ping_index(0)
    , ping_stamp()
    , centroid_x_px(0.0)
    , centroid_y_px(0.0)
    , bbox_x_px(0)
    , bbox_y_px(0)
    , bbox_width_px(0)
    , bbox_height_px(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _object_class_type;
  _object_class_type object_class;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef uint32_t _ping_index_type;
  _ping_index_type ping_index;

   typedef ros::Time _ping_stamp_type;
  _ping_stamp_type ping_stamp;

   typedef float _centroid_x_px_type;
  _centroid_x_px_type centroid_x_px;

   typedef float _centroid_y_px_type;
  _centroid_y_px_type centroid_y_px;

   typedef int32_t _bbox_x_px_type;
  _bbox_x_px_type bbox_x_px;

   typedef int32_t _bbox_y_px_type;
  _bbox_y_px_type bbox_y_px;

   typedef int32_t _bbox_width_px_type;
  _bbox_width_px_type bbox_width_px;

   typedef int32_t _bbox_height_px_type;
  _bbox_height_px_type bbox_height_px;





  typedef boost::shared_ptr< ::sss_package::GeolocatedObject_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sss_package::GeolocatedObject_<ContainerAllocator> const> ConstPtr;

}; // struct GeolocatedObject_

typedef ::sss_package::GeolocatedObject_<std::allocator<void> > GeolocatedObject;

typedef boost::shared_ptr< ::sss_package::GeolocatedObject > GeolocatedObjectPtr;
typedef boost::shared_ptr< ::sss_package::GeolocatedObject const> GeolocatedObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sss_package::GeolocatedObject_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sss_package::GeolocatedObject_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sss_package::GeolocatedObject_<ContainerAllocator1> & lhs, const ::sss_package::GeolocatedObject_<ContainerAllocator2> & rhs)
{
  return lhs.object_class == rhs.object_class &&
    lhs.confidence == rhs.confidence &&
    lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.ping_index == rhs.ping_index &&
    lhs.ping_stamp == rhs.ping_stamp &&
    lhs.centroid_x_px == rhs.centroid_x_px &&
    lhs.centroid_y_px == rhs.centroid_y_px &&
    lhs.bbox_x_px == rhs.bbox_x_px &&
    lhs.bbox_y_px == rhs.bbox_y_px &&
    lhs.bbox_width_px == rhs.bbox_width_px &&
    lhs.bbox_height_px == rhs.bbox_height_px;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sss_package::GeolocatedObject_<ContainerAllocator1> & lhs, const ::sss_package::GeolocatedObject_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sss_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sss_package::GeolocatedObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sss_package::GeolocatedObject_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sss_package::GeolocatedObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sss_package::GeolocatedObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sss_package::GeolocatedObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sss_package::GeolocatedObject_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sss_package::GeolocatedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "09b78b232110d33d86e8f0f2984e6e72";
  }

  static const char* value(const ::sss_package::GeolocatedObject_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x09b78b232110d33dULL;
  static const uint64_t static_value2 = 0x86e8f0f2984e6e72ULL;
};

template<class ContainerAllocator>
struct DataType< ::sss_package::GeolocatedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sss_package/GeolocatedObject";
  }

  static const char* value(const ::sss_package::GeolocatedObject_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sss_package::GeolocatedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string object_class\n"
"float32 confidence\n"
"\n"
"float64 latitude\n"
"float64 longitude\n"
"\n"
"uint32 ping_index\n"
"time ping_stamp\n"
"float32 centroid_x_px\n"
"float32 centroid_y_px\n"
"\n"
"int32 bbox_x_px\n"
"int32 bbox_y_px\n"
"int32 bbox_width_px\n"
"int32 bbox_height_px\n"
;
  }

  static const char* value(const ::sss_package::GeolocatedObject_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sss_package::GeolocatedObject_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_class);
      stream.next(m.confidence);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.ping_index);
      stream.next(m.ping_stamp);
      stream.next(m.centroid_x_px);
      stream.next(m.centroid_y_px);
      stream.next(m.bbox_x_px);
      stream.next(m.bbox_y_px);
      stream.next(m.bbox_width_px);
      stream.next(m.bbox_height_px);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GeolocatedObject_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sss_package::GeolocatedObject_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sss_package::GeolocatedObject_<ContainerAllocator>& v)
  {
    s << indent << "object_class: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.object_class);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "ping_index: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.ping_index);
    s << indent << "ping_stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.ping_stamp);
    s << indent << "centroid_x_px: ";
    Printer<float>::stream(s, indent + "  ", v.centroid_x_px);
    s << indent << "centroid_y_px: ";
    Printer<float>::stream(s, indent + "  ", v.centroid_y_px);
    s << indent << "bbox_x_px: ";
    Printer<int32_t>::stream(s, indent + "  ", v.bbox_x_px);
    s << indent << "bbox_y_px: ";
    Printer<int32_t>::stream(s, indent + "  ", v.bbox_y_px);
    s << indent << "bbox_width_px: ";
    Printer<int32_t>::stream(s, indent + "  ", v.bbox_width_px);
    s << indent << "bbox_height_px: ";
    Printer<int32_t>::stream(s, indent + "  ", v.bbox_height_px);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SSS_PACKAGE_MESSAGE_GEOLOCATEDOBJECT_H
