// Generated by gencpp from file sss_package/ImageMetadata.msg
// DO NOT EDIT!


#ifndef SSS_PACKAGE_MESSAGE_IMAGEMETADATA_H
#define SSS_PACKAGE_MESSAGE_IMAGEMETADATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/Image.h>
#include <marta_msgs/NavStatus.h>

namespace sss_package
{
template <class ContainerAllocator>
struct ImageMetadata_
{
  typedef ImageMetadata_<ContainerAllocator> Type;

  ImageMetadata_()
    : header()
    , image()
    , ping_indices()
    , ping_stamps()
    , nav_statuses()
    , nav_valid()
    , altitudes()
    , altitude_valid()
    , object_classes()
    , object_confidences()
    , object_centroid_x_px()
    , object_centroid_y_px()
    , object_bbox_x_px()
    , object_bbox_y_px()
    , object_bbox_width_px()
    , object_bbox_height_px()  {
    }
  ImageMetadata_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , image(_alloc)
    , ping_indices(_alloc)
    , ping_stamps(_alloc)
    , nav_statuses(_alloc)
    , nav_valid(_alloc)
    , altitudes(_alloc)
    , altitude_valid(_alloc)
    , object_classes(_alloc)
    , object_confidences(_alloc)
    , object_centroid_x_px(_alloc)
    , object_centroid_y_px(_alloc)
    , object_bbox_x_px(_alloc)
    , object_bbox_y_px(_alloc)
    , object_bbox_width_px(_alloc)
    , object_bbox_height_px(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::sensor_msgs::Image_<ContainerAllocator>  _image_type;
  _image_type image;

   typedef std::vector<uint32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint32_t>> _ping_indices_type;
  _ping_indices_type ping_indices;

   typedef std::vector<ros::Time, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<ros::Time>> _ping_stamps_type;
  _ping_stamps_type ping_stamps;

   typedef std::vector< ::marta_msgs::NavStatus_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::marta_msgs::NavStatus_<ContainerAllocator> >> _nav_statuses_type;
  _nav_statuses_type nav_statuses;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _nav_valid_type;
  _nav_valid_type nav_valid;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _altitudes_type;
  _altitudes_type altitudes;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _altitude_valid_type;
  _altitude_valid_type altitude_valid;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _object_classes_type;
  _object_classes_type object_classes;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _object_confidences_type;
  _object_confidences_type object_confidences;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _object_centroid_x_px_type;
  _object_centroid_x_px_type object_centroid_x_px;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _object_centroid_y_px_type;
  _object_centroid_y_px_type object_centroid_y_px;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _object_bbox_x_px_type;
  _object_bbox_x_px_type object_bbox_x_px;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _object_bbox_y_px_type;
  _object_bbox_y_px_type object_bbox_y_px;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _object_bbox_width_px_type;
  _object_bbox_width_px_type object_bbox_width_px;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _object_bbox_height_px_type;
  _object_bbox_height_px_type object_bbox_height_px;





  typedef boost::shared_ptr< ::sss_package::ImageMetadata_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sss_package::ImageMetadata_<ContainerAllocator> const> ConstPtr;

}; // struct ImageMetadata_

typedef ::sss_package::ImageMetadata_<std::allocator<void> > ImageMetadata;

typedef boost::shared_ptr< ::sss_package::ImageMetadata > ImageMetadataPtr;
typedef boost::shared_ptr< ::sss_package::ImageMetadata const> ImageMetadataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sss_package::ImageMetadata_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sss_package::ImageMetadata_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sss_package::ImageMetadata_<ContainerAllocator1> & lhs, const ::sss_package::ImageMetadata_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.image == rhs.image &&
    lhs.ping_indices == rhs.ping_indices &&
    lhs.ping_stamps == rhs.ping_stamps &&
    lhs.nav_statuses == rhs.nav_statuses &&
    lhs.nav_valid == rhs.nav_valid &&
    lhs.altitudes == rhs.altitudes &&
    lhs.altitude_valid == rhs.altitude_valid &&
    lhs.object_classes == rhs.object_classes &&
    lhs.object_confidences == rhs.object_confidences &&
    lhs.object_centroid_x_px == rhs.object_centroid_x_px &&
    lhs.object_centroid_y_px == rhs.object_centroid_y_px &&
    lhs.object_bbox_x_px == rhs.object_bbox_x_px &&
    lhs.object_bbox_y_px == rhs.object_bbox_y_px &&
    lhs.object_bbox_width_px == rhs.object_bbox_width_px &&
    lhs.object_bbox_height_px == rhs.object_bbox_height_px;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sss_package::ImageMetadata_<ContainerAllocator1> & lhs, const ::sss_package::ImageMetadata_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sss_package

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sss_package::ImageMetadata_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sss_package::ImageMetadata_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sss_package::ImageMetadata_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sss_package::ImageMetadata_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sss_package::ImageMetadata_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sss_package::ImageMetadata_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sss_package::ImageMetadata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b7d71bb022c02e7c92c518f300d617c9";
  }

  static const char* value(const ::sss_package::ImageMetadata_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb7d71bb022c02e7cULL;
  static const uint64_t static_value2 = 0x92c518f300d617c9ULL;
};

template<class ContainerAllocator>
struct DataType< ::sss_package::ImageMetadata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sss_package/ImageMetadata";
  }

  static const char* value(const ::sss_package::ImageMetadata_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sss_package::ImageMetadata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"sensor_msgs/Image image\n"
"\n"
"uint32[] ping_indices\n"
"time[] ping_stamps\n"
"marta_msgs/NavStatus[] nav_statuses\n"
"bool[] nav_valid\n"
"float32[] altitudes\n"
"bool[] altitude_valid\n"
"\n"
"string[] object_classes\n"
"float32[] object_confidences\n"
"float32[] object_centroid_x_px\n"
"float32[] object_centroid_y_px\n"
"int32[] object_bbox_x_px\n"
"int32[] object_bbox_y_px\n"
"int32[] object_bbox_width_px\n"
"int32[] object_bbox_height_px\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Image\n"
"# This message contains an uncompressed image\n"
"# (0, 0) is at top-left corner of image\n"
"#\n"
"\n"
"Header header        # Header timestamp should be acquisition time of image\n"
"                     # Header frame_id should be optical frame of camera\n"
"                     # origin of frame should be optical center of camera\n"
"                     # +x should point to the right in the image\n"
"                     # +y should point down in the image\n"
"                     # +z should point into to plane of the image\n"
"                     # If the frame_id here and the frame_id of the CameraInfo\n"
"                     # message associated with the image conflict\n"
"                     # the behavior is undefined\n"
"\n"
"uint32 height         # image height, that is, number of rows\n"
"uint32 width          # image width, that is, number of columns\n"
"\n"
"# The legal values for encoding are in file src/image_encodings.cpp\n"
"# If you want to standardize a new string format, join\n"
"# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n"
"\n"
"string encoding       # Encoding of pixels -- channel meaning, ordering, size\n"
"                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n"
"\n"
"uint8 is_bigendian    # is this data bigendian?\n"
"uint32 step           # Full row length in bytes\n"
"uint8[] data          # actual matrix data, size is (step * rows)\n"
"\n"
"================================================================================\n"
"MSG: marta_msgs/NavStatus\n"
"Header header\n"
"\n"
"marta_msgs/Position position\n"
" \n"
"marta_msgs/Euler orientation\n"
"\n"
"marta_msgs/Quaternion quaternion\n"
"\n"
"geometry_msgs/Vector3 ned_speed\n"
"\n"
"geometry_msgs/Vector3 omega_body\n"
"\n"
"uint8 gps_status\n"
"\n"
"bool initialized\n"
"\n"
"\n"
"================================================================================\n"
"MSG: marta_msgs/Position\n"
"float64 latitude\n"
"float64 longitude\n"
"float64 depth\n"
"\n"
"================================================================================\n"
"MSG: marta_msgs/Euler\n"
"float64 roll\n"
"float64 pitch\n"
"float64 yaw\n"
"\n"
"================================================================================\n"
"MSG: marta_msgs/Quaternion\n"
"float64 w\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::sss_package::ImageMetadata_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sss_package::ImageMetadata_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.image);
      stream.next(m.ping_indices);
      stream.next(m.ping_stamps);
      stream.next(m.nav_statuses);
      stream.next(m.nav_valid);
      stream.next(m.altitudes);
      stream.next(m.altitude_valid);
      stream.next(m.object_classes);
      stream.next(m.object_confidences);
      stream.next(m.object_centroid_x_px);
      stream.next(m.object_centroid_y_px);
      stream.next(m.object_bbox_x_px);
      stream.next(m.object_bbox_y_px);
      stream.next(m.object_bbox_width_px);
      stream.next(m.object_bbox_height_px);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImageMetadata_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sss_package::ImageMetadata_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sss_package::ImageMetadata_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "image: ";
    s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.image);
    s << indent << "ping_indices[]" << std::endl;
    for (size_t i = 0; i < v.ping_indices.size(); ++i)
    {
      s << indent << "  ping_indices[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.ping_indices[i]);
    }
    s << indent << "ping_stamps[]" << std::endl;
    for (size_t i = 0; i < v.ping_stamps.size(); ++i)
    {
      s << indent << "  ping_stamps[" << i << "]: ";
      Printer<ros::Time>::stream(s, indent + "  ", v.ping_stamps[i]);
    }
    s << indent << "nav_statuses[]" << std::endl;
    for (size_t i = 0; i < v.nav_statuses.size(); ++i)
    {
      s << indent << "  nav_statuses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::marta_msgs::NavStatus_<ContainerAllocator> >::stream(s, indent + "    ", v.nav_statuses[i]);
    }
    s << indent << "nav_valid[]" << std::endl;
    for (size_t i = 0; i < v.nav_valid.size(); ++i)
    {
      s << indent << "  nav_valid[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.nav_valid[i]);
    }
    s << indent << "altitudes[]" << std::endl;
    for (size_t i = 0; i < v.altitudes.size(); ++i)
    {
      s << indent << "  altitudes[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.altitudes[i]);
    }
    s << indent << "altitude_valid[]" << std::endl;
    for (size_t i = 0; i < v.altitude_valid.size(); ++i)
    {
      s << indent << "  altitude_valid[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.altitude_valid[i]);
    }
    s << indent << "object_classes[]" << std::endl;
    for (size_t i = 0; i < v.object_classes.size(); ++i)
    {
      s << indent << "  object_classes[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.object_classes[i]);
    }
    s << indent << "object_confidences[]" << std::endl;
    for (size_t i = 0; i < v.object_confidences.size(); ++i)
    {
      s << indent << "  object_confidences[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.object_confidences[i]);
    }
    s << indent << "object_centroid_x_px[]" << std::endl;
    for (size_t i = 0; i < v.object_centroid_x_px.size(); ++i)
    {
      s << indent << "  object_centroid_x_px[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.object_centroid_x_px[i]);
    }
    s << indent << "object_centroid_y_px[]" << std::endl;
    for (size_t i = 0; i < v.object_centroid_y_px.size(); ++i)
    {
      s << indent << "  object_centroid_y_px[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.object_centroid_y_px[i]);
    }
    s << indent << "object_bbox_x_px[]" << std::endl;
    for (size_t i = 0; i < v.object_bbox_x_px.size(); ++i)
    {
      s << indent << "  object_bbox_x_px[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.object_bbox_x_px[i]);
    }
    s << indent << "object_bbox_y_px[]" << std::endl;
    for (size_t i = 0; i < v.object_bbox_y_px.size(); ++i)
    {
      s << indent << "  object_bbox_y_px[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.object_bbox_y_px[i]);
    }
    s << indent << "object_bbox_width_px[]" << std::endl;
    for (size_t i = 0; i < v.object_bbox_width_px.size(); ++i)
    {
      s << indent << "  object_bbox_width_px[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.object_bbox_width_px[i]);
    }
    s << indent << "object_bbox_height_px[]" << std::endl;
    for (size_t i = 0; i < v.object_bbox_height_px.size(); ++i)
    {
      s << indent << "  object_bbox_height_px[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.object_bbox_height_px[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SSS_PACKAGE_MESSAGE_IMAGEMETADATA_H
