# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from sss_package/GeolocatedObject.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class GeolocatedObject(genpy.Message):
  _md5sum = "09b78b232110d33d86e8f0f2984e6e72"
  _type = "sss_package/GeolocatedObject"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string object_class
float32 confidence

float64 latitude
float64 longitude

uint32 ping_index
time ping_stamp
float32 centroid_x_px
float32 centroid_y_px

int32 bbox_x_px
int32 bbox_y_px
int32 bbox_width_px
int32 bbox_height_px
"""
  __slots__ = ['object_class','confidence','latitude','longitude','ping_index','ping_stamp','centroid_x_px','centroid_y_px','bbox_x_px','bbox_y_px','bbox_width_px','bbox_height_px']
  _slot_types = ['string','float32','float64','float64','uint32','time','float32','float32','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       object_class,confidence,latitude,longitude,ping_index,ping_stamp,centroid_x_px,centroid_y_px,bbox_x_px,bbox_y_px,bbox_width_px,bbox_height_px

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GeolocatedObject, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.object_class is None:
        self.object_class = ''
      if self.confidence is None:
        self.confidence = 0.
      if self.latitude is None:
        self.latitude = 0.
      if self.longitude is None:
        self.longitude = 0.
      if self.ping_index is None:
        self.ping_index = 0
      if self.ping_stamp is None:
        self.ping_stamp = genpy.Time()
      if self.centroid_x_px is None:
        self.centroid_x_px = 0.
      if self.centroid_y_px is None:
        self.centroid_y_px = 0.
      if self.bbox_x_px is None:
        self.bbox_x_px = 0
      if self.bbox_y_px is None:
        self.bbox_y_px = 0
      if self.bbox_width_px is None:
        self.bbox_width_px = 0
      if self.bbox_height_px is None:
        self.bbox_height_px = 0
    else:
      self.object_class = ''
      self.confidence = 0.
      self.latitude = 0.
      self.longitude = 0.
      self.ping_index = 0
      self.ping_stamp = genpy.Time()
      self.centroid_x_px = 0.
      self.centroid_y_px = 0.
      self.bbox_x_px = 0
      self.bbox_y_px = 0
      self.bbox_width_px = 0
      self.bbox_height_px = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.object_class
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_f2d3I2f4i().pack(_x.confidence, _x.latitude, _x.longitude, _x.ping_index, _x.ping_stamp.secs, _x.ping_stamp.nsecs, _x.centroid_x_px, _x.centroid_y_px, _x.bbox_x_px, _x.bbox_y_px, _x.bbox_width_px, _x.bbox_height_px))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.ping_stamp is None:
        self.ping_stamp = genpy.Time()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_class = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.object_class = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.confidence, _x.latitude, _x.longitude, _x.ping_index, _x.ping_stamp.secs, _x.ping_stamp.nsecs, _x.centroid_x_px, _x.centroid_y_px, _x.bbox_x_px, _x.bbox_y_px, _x.bbox_width_px, _x.bbox_height_px,) = _get_struct_f2d3I2f4i().unpack(str[start:end])
      self.ping_stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.object_class
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_f2d3I2f4i().pack(_x.confidence, _x.latitude, _x.longitude, _x.ping_index, _x.ping_stamp.secs, _x.ping_stamp.nsecs, _x.centroid_x_px, _x.centroid_y_px, _x.bbox_x_px, _x.bbox_y_px, _x.bbox_width_px, _x.bbox_height_px))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.ping_stamp is None:
        self.ping_stamp = genpy.Time()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_class = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.object_class = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.confidence, _x.latitude, _x.longitude, _x.ping_index, _x.ping_stamp.secs, _x.ping_stamp.nsecs, _x.centroid_x_px, _x.centroid_y_px, _x.bbox_x_px, _x.bbox_y_px, _x.bbox_width_px, _x.bbox_height_px,) = _get_struct_f2d3I2f4i().unpack(str[start:end])
      self.ping_stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_f2d3I2f4i = None
def _get_struct_f2d3I2f4i():
    global _struct_f2d3I2f4i
    if _struct_f2d3I2f4i is None:
        _struct_f2d3I2f4i = struct.Struct("<f2d3I2f4i")
    return _struct_f2d3I2f4i
