(cl:in-package sss_package-msg)
(cl:export '(HEADER-VAL
          HEADER
          IMAGE-VAL
          IMAGE
          PING_INDICES-VAL
          PING_INDICES
          PING_STAMPS-VAL
          PING_STAMPS
          NAV_STATUSES-VAL
          NAV_STATUSES
          NAV_VALID-VAL
          NAV_VALID
          ALTITUDES-VAL
          ALTITUDES
          ALTITUDE_VALID-VAL
          ALTITUDE_VALID
          OBJECT_CLASSES-VAL
          OBJECT_CLASSES
          OBJECT_CONFIDENCES-VAL
          OBJECT_CONFIDENCES
          OBJECT_CENTROID_X_PX-VAL
          OBJECT_CENTROID_X_PX
          OBJECT_CENTROID_Y_PX-VAL
          OBJECT_CENTROID_Y_PX
          OBJECT_BBOX_X_PX-VAL
          OBJECT_BBOX_X_PX
          OBJECT_BBOX_Y_PX-VAL
          OBJECT_BBOX_Y_PX
          OBJECT_BBOX_WIDTH_PX-VAL
          OBJECT_BBOX_WIDTH_PX
          OBJECT_BBOX_HEIGHT_PX-VAL
          OBJECT_BBOX_HEIGHT_PX
))